<div class="">

<h2>View Layer examples</h2>

<p>Some examples of controlling the view-layer using view models</p>
<ul>
    <li><a href="<?php echo $this->url('view', array('action'=>'index'));?>">Default rendering</a></li>
</ul>

Changing scripts:
<ul>
    <li><a href="<?php echo $this->url('view', array('action'=>'nolayout'));?>">No layout</a></li>
    <li><a href="<?php echo $this->url('view', array('action'=>'different-layout'));?>">Choose a different layout</a></li>
    <li><a href="<?php echo $this->url('view', array('action'=>'different-view-script'));?>">Choose a different view script</a></li>
</ul>


Multiple view models:
<ul>
    <li><a href="<?php echo $this->url('view', array('action'=>'addAnotherViewModelToLayout'));?>">
        Add an additional view model to layout</a></li>
    <li><a href="<?php echo $this->url('view', array('action'=>'multipleViewModels'));?>">
        Multiple view models</a></li>
    
</ul>



Response:
<ul>
    <li><a href="<?php echo $this->url('view', array('action'=>'respond'));?>">Send a 501 response</a></li>
</ul>


<h2>Source code</h2>
<p>The source code is on <a href="https://github.com/akrabat/ZF2TestApp/tree/master/module/Application">GitHub</a></p>
<ul>
    <li><a href="https://github.com/akrabat/ZF2TestApp/blob/master/module/Application/src/Application/Controller/ViewController.php">ViewController.php</a></li>
    <li><a href="https://github.com/akrabat/ZF2TestApp/tree/master/module/Application/view/view">View scripts</a></li>
    <li><a href="https://github.com/akrabat/ZF2TestApp/tree/master/module/Application/view/layout">Layouts</a></li>
</ul>

</div>