<?php 
$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);

$basePath = $this->basePath();
$this->headLink()->appendStylesheet($basePath . '/css/bootstrap.min.css')
                 ->appendStylesheet($basePath . '/css/style.css')
                 ->appendStylesheet($basePath . '/css/bootstrap-responsive.min.css');

$this->headLink(array(
            'rel'  => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $basePath . '/images/favicon.ico',
        ));

// HTML5 shim, for IE6-8 support of HTML elements
$this->headScript()->appendFile($basePath . '/js/html5.js', 'text/javascript', 
    array('conditional' => 'lt IE9',));

echo $this->doctype();
?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 Test Application') ?>

    <?php echo $this->headMeta() ?>

    <!-- Le styles -->
    <?php echo $this->headLink() ?>
    
    <!-- Scripts -->
    <?php echo $this->headScript() ?>

  </head>

  <body class="another-layout">

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url('home') ?>">Test Application: Another Layout</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="<?php echo $this->url('home') ?>">Home</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container body">

      <p>Layout script: layout/another.phtml</p>
      
      <?php echo $this->content; ?>

      <hr>
      <?php echo $this->footer; ?>

    </div> <!-- /container -->

  </body>
</html>
